# Generated by Django 4.2.3 on 2023-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profile_photo', models.ImageField(upload_to='')),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
