# Generated by Django 4.2.3 on 2023-07-28 15:46

import car_shop.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', car_shop.account.models.AppUserManager()),
            ],
        ),
    ]
