# Generated by Django 4.2.3 on 2023-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_person_last_name_alter_person_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
