# Generated by Django 4.2.3 on 2023-07-24 17:12

import car_shop.account.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_person_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[car_shop.account.validators.check_name, django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[car_shop.account.validators.check_name, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
