# Generated by Django 4.2.3 on 2023-07-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonenumber',
            name='telephone_number',
            field=models.IntegerField(),
        ),
    ]
