# Generated by Django 4.2.3 on 2023-08-10 20:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonenumber',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='BG'),
        ),
    ]
