# Generated by Django 4.2.3 on 2023-08-04 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_delete_person_alter_appuser_managers'),
        ('common', '0005_alter_person_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('image_of_the_product', models.ImageField(upload_to='ordered_products_images')),
                ('type_of_product', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('confirm_purchase_of_product', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('PR', 'Processing order'), ('PT', 'Pending tracking event'), ('TR', 'Tracking Info Received'), ('IT', 'In transit'), ('OD', 'Out for delivery'), ('DE', 'Delivered')], default='PN')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='BG')),
                ('total_price', models.IntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shoppingcart')),
            ],
        ),
    ]
