# Generated by Django 4.2.3 on 2023-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_shoppingcart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='common.shoppingcart'),
        ),
    ]
