# Generated by Django 4.2.3 on 2023-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_the_product', models.ImageField(upload_to='product_images')),
                ('for_car', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('specifications', models.CharField(max_length=500)),
                ('category_of_product', models.CharField(choices=[('BS', 'Braking system'), ('DT', 'Drivetrain'), ('EN', 'Engine')])),
                ('type_of_product', models.CharField(choices=[('BP', 'Braking pads'), ('BR', 'Braking rotors'), ('BC', 'Braking cylinders'), ('DSA', 'Drivetrain semi axle box'), ('DDS', 'Drivetrain drive shaft'), ('DHA', 'Drivetrain half axle'), ('EV', 'Engine valves'), ('ECD', 'Engine chain drive'), ('ECP', 'Engine cam shaft pulley')])),
                ('price', models.IntegerField()),
            ],
        ),
    ]
