# Generated by Django 4.2.3 on 2023-08-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrakeCylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_brake_cylinder', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=15)),
                ('manufacturer', models.CharField(max_length=10)),
                ('diameter_of_piston', models.IntegerField()),
                ('brake_system', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('commercial_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BrakePads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_brake_pads', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=15)),
                ('manufacturer', models.CharField(max_length=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('price', models.IntegerField()),
                ('commercial_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BrakeRotors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_brake_rotors', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=15)),
                ('manufacturer', models.CharField(max_length=10)),
                ('diameter', models.IntegerField()),
                ('center_hole_diameter', models.IntegerField()),
                ('number_of_holes', models.IntegerField()),
                ('price', models.IntegerField()),
                ('commercial_number', models.IntegerField()),
            ],
        ),
    ]
