# Generated by Django 4.2.3 on 2023-08-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrakeCylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_brake_cylinder', models.ImageField(blank=True, null=True, upload_to='product_images/brake_parts/cylinder')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('diameter_of_piston', models.IntegerField()),
                ('brake_system', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('commercial_number', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='BrakePads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_brake_pads', models.ImageField(blank=True, null=True, upload_to='product_images/brake_parts/pads')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('price', models.IntegerField()),
                ('commercial_number', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='BrakeRotors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_brake_rotors', models.ImageField(blank=True, null=True, upload_to='product_images/brake_parts/rotors')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('diameter', models.IntegerField()),
                ('number_of_holes', models.IntegerField()),
                ('price', models.IntegerField()),
                ('commercial_number', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveTrainDriveShaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_drivetrain_drive_shaft', models.ImageField(blank=True, null=True, upload_to='product_images/drivetrain_parts/drive_shaft')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('side_of_mounting', models.CharField(max_length=30)),
                ('length', models.IntegerField()),
                ('production_number', models.CharField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveTrainHalfAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_drivetrain_half_axle', models.ImageField(blank=True, null=True, upload_to='product_images/drivetrain_parts/half_axle')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('type_of_transmission', models.CharField(max_length=30)),
                ('side_of_mounting', models.CharField(max_length=30)),
                ('abs_ring', models.IntegerField()),
                ('count_of_abs_rings', models.IntegerField()),
                ('length', models.IntegerField()),
                ('type_of_carving', models.CharField(max_length=30)),
                ('number_of_holes', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DriveTrainSemiAxleBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_drivetrain_semi_axle_box', models.ImageField(blank=True, null=True, upload_to='product_images/drivetrain_parts/semi_axle_box')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('type_of_transmission', models.CharField(max_length=30)),
                ('side_of_mounting', models.CharField(max_length=30)),
                ('driving_axis', models.CharField(max_length=30)),
                ('length', models.IntegerField()),
                ('surface', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineChainDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_engine_chain_drive', models.ImageField(blank=True, null=True, upload_to='product_images/engine_parts/chain_drive')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineValves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_of_product_engine_valve', models.ImageField(blank=True, null=True, upload_to='product_images/engine_parts/valve')),
                ('for_car', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('batch_number', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('type_of_valve', models.CharField(max_length=30)),
                ('type_of_exploitation', models.CharField(max_length=30)),
                ('operating_current', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
