# Generated by Django 4.2.3 on 2023-08-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_of_the_product',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
